import fs from 'fs';
import standardVersion from 'standard-version';

const TMP_VERSION_HOLDER = 'autogenerated.version.json';
const CURRENT_VERSION_SOURCE = 'lerna.json';

fs.writeFileSync(TMP_VERSION_HOLDER, JSON.stringify({}), { encoding: 'utf-8' });

standardVersion({
	bumpFiles: [{ filename: TMP_VERSION_HOLDER, type: 'json' }],
	packageFiles: [{ filename: CURRENT_VERSION_SOURCE, type: 'json' }],
	dryRun: false,
	silent: true,
	skip: {
		changelog: true,
		commit: true,
		tag: true
	}
}).then(() => {
	const tmpVersionHolderRaw = fs.readFileSync(TMP_VERSION_HOLDER, { encoding: 'utf-8' });
	const proposedVersion = JSON.parse(tmpVersionHolderRaw).version;
	console.info(proposedVersion);
}).finally(() => fs.unlinkSync(TMP_VERSION_HOLDER));