#!/usr/bin/env node
const
	fp = require('lodash/fp'),
	glob = require('glob'),
	kefir = require('kefir'),
	parseArgs = require('minimist'),
	{ writeFile } = require('fs'),
	{ join: joinPath, extname: getExtension, basename: getBase, dirname: getDir } = require('path'),
	{ render: renderSass } = require('sass');

const { path:basePath = "." } = parseArgs(process.argv.slice(2));

console.time('Total');

const
	fileStreamFromGlob = (path)=> kefir.fromNodeCallback(fp.partial(glob, [path])).flatten(),
	tsTemplate = (css)=> [
		"// autogenerated module",
		"import {css} from 'lit-element';",
		["export const style = css`", css, "`;"].join('')
	].join('\n'),
	prefixWith = (path)=> (pre)=> joinPath(...[getDir(path), [pre, getBase(path)].join('')]),
	suffixWith = (path)=> (suf)=> joinPath(...[getDir(path), [getBase(path), suf].filter(Boolean).join('.')]);

fileStreamFromGlob(joinPath(process.cwd(), basePath, '**/*.s[ac]ss'))
	.flatMapConcat((sassFile)=> {
		return kefir.fromNodeCallback((cb)=>
			renderSass({
				importer: (path, prev, done)=> {
					kefir
						.concat(
							["", "_"]
								.map(prefixWith(path))
								.flatMap((basePath)=> ["", "scss", "sass"].map(suffixWith(basePath)))
								.map((probePath)=> kefir.fromNodeCallback((cb) => {
									const res = fp.attempt(() => require.resolve(probePath));
									cb(fp.isError(res) && res, res);
								}))
						)
						.ignoreErrors()
						.map((outPath)=> ({ file: outPath }))
						.beforeEnd(fp.noop)
						.take(1)
						.onValue(done);
				},
				file: sassFile,
				outputStyle: "compressed"
			}, cb)
		)
		.map(({ css })=>({
			sass_path: sassFile,
			css: css.toString()
		}));
	})
	.map(({ css, ...rest })=> {
		return {
			module_content: tsTemplate(css),
			...rest
		};
	})
	.flatMap(({ sass_path, module_content })=> {
		const outputPath = joinPath(...[getDir(sass_path), [getBase(sass_path, getExtension(sass_path)), 'css.ts'].join('.')]);
		return kefir.fromNodeCallback((cb)=>
			writeFile(outputPath, module_content, cb)
		).map(()=> ` ✔ ${outputPath}`)
	})
	.onValue(console.log)
	.onEnd(()=> console.timeEnd('Total'));