name: Deploy Storybook

on:
  push:
    branches: [viv-25*]

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn

      - name: Build code
        run: yarn build

      - name: Build storybook
        run: yarn storybook:build

      - name: Deploy storybook
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: './storybook-static'
          DEST_DIR: '/storybook'
