name: Generate icons

on:
  push:
    branches:
      - new-icon-strategy

jobs:
  build-deploy-demo-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_AT }}
      - name: Setup NodeJS 12
          uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
          run: |
            npm install -g yarn
            yarn install
      # Build and publish
      - name: Build components
        run: yarn compile
      - name: Build icon resolver
        run: yarn build:icon-resolver --awsAccessKey=${{ secrets.AWS_ACCESS_KEY_ID_B }} --awsAccessSecret=${{ secrets.AWS_ACCESS_KEY_SECRET_B }} --awsBucketName=vivid-icons-dev