name: Compile & Test Sanity

on:
  push:
    branches:
      - master

jobs:
  cache-yarn-and-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: vivid-cache-yarn-${{ hashFiles('**/package.json') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        env:
          yarn_always_auth: true,
          yarn__auth: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          yarn_registry: "https://vonagecc.jfrog.io/vonagecc/api/npm/npm/"
        run: yarn install --network-timeout 100000

      - name: Build components
        run: yarn compile

      - name: Cache build
        uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            common
            components
          key: vivid-cache-build-${{ github.sha }}

  test-safari:
    needs: cache-yarn-and-build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: vivid-cache-yarn-${{ hashFiles('**/package.json') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        env:
          yarn_always_auth: true,
          yarn__auth: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          yarn_registry: "https://vonagecc.jfrog.io/vonagecc/api/npm/npm/"
        run: yarn install --network-timeout 100000

      - name: Cache build
        uses: actions/cache@v2
        id: build-cache
        with:
          path: |
            common
            components
          key: vivid-cache-build-${{ github.sha }}

      - name: Build components
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn compile

      - name: Test components
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_ACCESS }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_SECRET }}
        run: yarn test:bs --browsers=Safari_13_BS
