name: Compile & Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pr-title-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Lint Pull Request Title
        uses: YonatanKra/simple-conventional-pr-title-gitaction@v2.0.1