name: "Lint PR"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout and install dependencies
        run: npm install @actions/core @actions/github @commitlint/config-conventional @commitlint/lint @commitlint/load

      - name: Checks the PR title
        run: node ./scripts/pr-lint