name: Build & Deploy Demo Versioned Deploy

on:
  push:
    branches:
      - viv-44-iss-43-storybook

jobs:
  build-and-deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Create deploy timestamp
        run: echo '::set-env name=SB_VERSION::(date +"%y-%m-%d-%H-%M-%S")'

      - name: Test timestamp
        run: export SB_VERSION