name: build & test ${{github.ref}}

on:
  push:
    branches: [develop, viv-*, iss-*]

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      #  - name: build storybook
      #    run: yarn storybook:build

      # - name: ZEIT Now Deployment
      #   uses: amondnet/now-deployment@v2.0.1
      #     with:
      #       zeit-token: ${{secrets.ZEIT_TOKEN}}
      #       now-org-id: ${{secrets.ZEIT_ORG_ID}}
      #       now-project-id: ${{secrets.ZEIT_PROJECT_ID}}
      #       working-directory: ./storybook-static
      #       # now-args: "--prod" #Optional
