name: develop build

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install yarn globally
        run: npm install -g yarn

      - name: install components with yarn
        run: yarn

      #       - name: test
      #         run: yarn test

      - name: build
        run: yarn build

      - name: build storybook
        run: yarn storybook:build

      - name: ZEIT Now Deployment
        uses: amondnet/now-deployment@v2.0.1
        with:
          zeit-token: ${{secrets.ZEIT_TOKEN}}
          now-org-id: "team_OZGLAGZ967yUKWH9tzPPqvXU"
          now-project-id: "QmRRAhPzCqLo1i3YDa6YPuRjm9KGrkPJc7ApSfXK5thydr"
          working-directory: ./storybook-static,
          now-args: "--prod" #Optional

