name: build & test

on:
  push:
    branches: [develop, viv-*, iss-*]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
#           repository: my-org/my-private-tools
#           token: ${{ secrets.CI_PAT }}
#           ssh-key: ${{ secrets.SSH_KEY }}
          submodules: true

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      # - name: build storybook
      #   run: yarn storybook:build

      - name: Vercel deployment
        uses: amondnet/vercel-action@v19
#         uses: amondnet/now-deployment@v2
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          # working-directory: ./storybook-static
          working-directory: ./dist
          vercel-args: '--prod' #Optional
