name: "Lint PR Title"

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn add -W @commitlint/config-conventional
    - uses: JulienKode/pull-request-name-linter-action@v0.2.0
