name: Node.js Packages Publish

on:
  push:
    branches: [testrel-*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install yarn globally
        run: npm install -g yarn

      - name: install packages with yarn (will run lerna bootstrap postinstall)
        run: yarn install

      - name: build
        run: yarn compile

      - name: bump version
        run: yarn lerna version 0.0.4 --no-git-tag-version --no-private --yes

      - name: commit and push the new version
        run: >
          git config user.email "vivid.ci@vonage.com" &&
          git config user.name "Vivid CI" &&
          git add --all &&
          git commit -m "bumping the version to 0.0.3" &&
          git push

      - name: create PR to the master
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          branch: master