name: Master Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
    branches:
      - master

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 15
    if: github.event.pull_request.draft == false
    name: Build
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Push changes
        run: |
          'fsdf' >> newFileToSave.json
          git fetch
          git config user.email "vivid@vonage.com"
          git config user.name "Vivid"
          git add --all
          git commit -m "update versions to ${{ env.RELEASE_VERSION }}"
          git push


