name: Release Vivid Changelog

on: [push, workflow_dispatch]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_AT }}

      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
          git tag v0.5.3

      # Notify community
      - name: Build changelog for Slack notification
        id: export_message
        run: echo "::set-output name=message::$(npx conventional-changelog-cli --preset angular --release-count 1)"

      - name: Notify slack mock
        run: echo 'Changelog - ' "$steps.export_message.outputs.message"
        
