name: Testing removal of PATs

on:
  push

jobs:
  prepare-verify:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_EMAIL: vivid@vonage.com
      GIT_AUTHOR_NAME: Vividbot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - run: echo "Hello World" > test.txt
      - run: git add test.txt
      - run: git config --global user.email "vivid@vonage.com"
      - run: git config --global user.name "Vivid"

      - run: git checkout -b this_is_a_test_branch_please_delete_me

      - run: git commit -a -m "Testing push to master without the use of PATs" --author="Vivid <vivid@vonage.com>"

      - run: git push
