name: Testing removal of PATs

on:
  push

jobs:
  prepare-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.VIVID_TOKEN }}

      - run: rm test.txt
      - run: git add test.txt
      - run: git config user.email "vivid@vonage.com"
      - run: git config user.name "Vivid"

      - run: git commit -a -m "Testing push to master without the use of PATs" --author="Vivid <vivid@vonage.com>"

      - run: git push
