name: Test Script

on:
  push:
    branches:
      - new-icon-strategy

jobs:
  build-deploy-demo-dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_B }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET_B }}

    steps:
      - name: Notify slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'vivid-test'
          MSG_MINIMAL: true
          SLACK_ICON_EMOJI: ':vivid:'
          SLACK_USERNAME: Vivid CI
          SLACK_TITLE: ${{ secrets.AWS_ACCESS_KEY_ID_B }}
          SLACK_MESSAGE: ${{ secrets.AWS_ACCESS_KEY_SECRET_B }}