name: Test

on:
  push

jobs:
  up:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          yarn_always_auth: true
          yarn__auth: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          yarn_registry: "https://vonagecc.jfrog.io/vonagecc/api/npm/npm/"
      - run: du -sh
      - uses: Vonage/beame@v0.1
  down:
    runs-on: ubuntu-18.04
    needs: up
    steps:
      - uses: Vonage/beame@v0.1
        with:
          direction: down
      - run: du -sh
