name: Release Vivid

on:
  push:
    branches:
      - release_announcer

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_AT }}

      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      # Build and publish
      - name: Build components
        run: yarn compile

      - name: Notify slack
        run: git log --format=oneline --decorate=short | node ./scripts/release_announcer --slackHookUrl="https://hooks.slack.com/services/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"

