name: Test Github Actions

on:
  push:
    branches:
      - remove-export-script

jobs:
  create-release-message:
    name: Create Release Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Description
        id: export_message
        run: |
          description="$(npx conventional-changelog-cli --preset angular --release-count 5)"
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=message::$description"
      - name: Test
        run: echo ${{steps.export_message.outputs.message}}