name: Test Yonatan

on:
  push:
    branches:
      - 'VIV-70/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Git log
        run: git log --format=%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci%n

      - name: Install yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn add @actions/core conventional-changelog-cli -W

      - name: Get the changes
        run: yarn changelog:publish

      - name: Print the changes
        run: echo $VERSION_CHANGE_LOG