name: Test Script

on:
  push:
    branches:
      - release_announcer

jobs:
  build-deploy-demo-dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_VIVID_DEMO_PROD_ACCESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_VIVID_DEMO_PROD_SECRET }}

    steps:
      - name: Notify slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'vivid-test'
          MSG_MINIMAL: true
          SLACK_ICON_EMOJI: ':vivid:'
          SLACK_USERNAME: Vivid CI
          SLACK_TITLE: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Hello