name: Release
on:
  push
jobs:
  post_publish:
    name: Post publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2

      ### REMOVE
      - run: npm install lodash split minimist kefir semver-diff

      # Notify community
      - name: Notify slack
        run: git log --format=oneline --decorate=short | node ./scripts/release_announcer --slackHookUrl="${{ secrets.SLACK_WEBHOOK }}"
