name: Test Github Actions

on:
  push:
    branches:
      - remove-export-script

jobs:
  create-release-message:
    name: Create Release Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v2
      - name: Setup NodeJS 12
          uses: actions/setup-node@v1
          with:
            node-version: 12
      - name: Build changelog for Slack notification
          id: export_message
          run: echo "::set-output name=message::$(npx conventional-changelog --preset angular --release-count 1)"
      - name: Test
          run: echo ${steps.export_message.outputs.message}