name: Test Github Actions

on:
  push:
    branches:
      - remove-export-script

jobs:
  create-release-message:
    name: Create Release Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.CI_AT }}
      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Description
        id: export_message
        run: |
          description="$(npx conventional-changelog-cli --preset angular --release-count 1)"
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=message::$description"
      - name: Notify slack
        uses: rtCamp/action-slack-notify@master
        env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
         SLACK_CHANNEL: 'vivid-core'
         MSG_MINIMAL: true
         SLACK_ICON_EMOJI: ':vivid:'
         SLACK_USERNAME: Vivid CI
         SLACK_TITLE: Vivid Release Notice
         SLACK_MESSAGE: Hey!!! We've just released a new Vivid!!! ${{ steps.export_message.outputs.message }}